### ISSUE TITLE
Sync - invalid destination 

### ISSUE THREAD

**Issue by richp10** [koblas/s3-cli#1]
great project!

I cannot get sync to work - with error 'Invalid destination argument'. 

Am using s3://mybucketname - and this worked for a cp - but isn't working for sync.

**Comment by koblas** [comment]
Any other details?  Sync is actually built on the same internals as `cp`. I just pushed a fix to give a bit better error messages to the output which might help you track down the problem.

**Comment by koblas** [comment]
No further feedback, unable to reproduce.
