### ISSUE TITLE
Does s3-cli support s3 endpoint which build by myself?

### ISSUE THREAD

**Issue by silenceli** [koblas/s3-cli#10]
does s3-cli only support AWS s3 storage?

**Comment by koblas** [comment]
At the moment it only supports AWS S3 storage.

**Comment by gadelkareem** [comment]
Any chance to test it against scaleway storage https://www.scaleway.com/en/object-storage/ ? s3cmd already works with it but I tested s3-cli and got `AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'nl-ams'
        status code: 400, request id: tx77d27e547a485a03-005cda48, host id: tx77d2367a485a03-005cd45a48`
