### ISSUE TITLE
EmptyStaticCreds: static credentials are empty

### ISSUE THREAD

**Issue by ZhuBicen** [koblas/s3-cli#11]
It always prompt: EmptyStaticCreds: static credentials are empty
Even  I have specified the cfg file. and the cfg file works well if using s3cmd
`./s3-cli -c s3cfg ls s3://xxx`

**Comment by naftulikay** [comment]
I am also affected by this.

**Comment by koblas** [comment]
Any possibility of getting a redacted version of your `s3cfg` to make sure I'm testing the right thing?

**Comment by naftulikay** [comment]
It was exactly as specified in the demo:

```
[default]
access_key = foo
secret_key = bar
```

There may have not been spaces between equals and the value `access_key=$ACCESS_KEY`.

**Comment by naftulikay** [comment]
For what it's worth, I also tried just using AWS credentials via environment variables and got the same result. I also used the CLI flags to specify the keys at process start time. None of these worked. I'm on Ubuntu 16.04 amd64 if that's helpful.

**Comment by vincentfiestada** [comment]
I'm getting the same error, but I was expecting it to support IAM roles. Does it not support this?

**Comment by delfer** [comment]
Fix:
```diff
--- a/config.go
+++ b/config.go
@@ -62,7 +62,12 @@ func loadConfigFile(path string) *Config {

        // fmt.Println("Read config ", path)

-       if err := ini.MapTo(config, path); err != nil {
+       cfg, err := ini.Load(path)
+       if err != nil {
+               return config
+       }
+
+       if err := cfg.Section("default").MapTo(config); err != nil {
                return config
        }
```

**Comment by koblas** [comment]
Can you make a PR?

**Comment by delfer** [comment]
@koblas https://github.com/koblas/s3-cli/pull/12

**Comment by koblas** [comment]
The pull request from @delfer was merged.  Please let me know if you continue to have problems.

**Comment by yangpandi** [comment]
any one can help me how to resolve this question?

**Comment by ganeshkumar-opscruise** [comment]
facing this issue while trying to use s3 as storage with the version 2.4.0, any help to resolve this issue

**Comment by koblas** [comment]
I'll take a look, though tempted to upgrade to the v2 golang APIs since they're usable...
