### ISSUE TITLE
endpoint 

### ISSUE THREAD

**Issue by rrkanna** [koblas/s3-cli#13]
Hi 

How do we set the custom host endpoint, doesn't seem to take this into effect from .s3cfg

host_base =
host_bucket =

is there way to set this ?

**Comment by koblas** [comment]
Didn't have support for those, but just added it.  I don't have any way to test, so please let me know if it works.

**Comment by rrkanna** [comment]
looks it got runtime errors now

./s3-cli ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x14f9415]

goroutine 1 [running]:
github.com/go-ini/ini.(*Key).transformValue(0xc0001fd1f0, 0xc000142271, 0x22, 0x1501ccb, 0xc00022005c)
	/Users/rrk/go/src/github.com/go-ini/ini/key.go:147 +0xa5
github.com/go-ini/ini.(*Key).String(...)
	/Users/rrk/go/src/github.com/go-ini/ini/key.go:154
github.com/go-ini/ini.setWithProperType(0x17d8dc0, 0x159f2a0, 0xc0001fd1f0, 0x159f2a0, 0xc00021e038, 0x198, 0x167f8f2, 0x1, 0x1570000, 0x11, ...)
	/Users/rrk/go/src/github.com/go-ini/ini/struct.go:156 +0x7df
github.com/go-ini/ini.(*Section).mapTo(0xc0001fc3f0, 0x165cee0, 0xc00021e000, 0x199, 0xc00021e000, 0x199, 0xc0000a6660)
	/Users/rrk/go/src/github.com/go-ini/ini/struct.go:264 +0x3fd
github.com/go-ini/ini.(*Section).MapTo(0xc0001fc3f0, 0x158a960, 0xc00021e000, 0xc0001fc3f0, 0x0)
	/Users/rrk/go/src/github.com/go-ini/ini/struct.go:283 +0x1c1
main.loadConfigFile(0xc00021c000, 0x16, 0x2)
	/Users/rrk/go/src/github.com/koblas/s3-cli/config.go:74 +0x11c
main.NewConfig(0xc0000a42c0, 0xc0001a13f0)
	/Users/rrk/go/src/github.com/koblas/s3-cli/config.go:52 +0x8a
main.main.func1.1(0xc0000a42c0, 0xc00020a100, 0xc0000a42c0)
	/Users/rrk/go/src/github.com/koblas/s3-cli/main.go:81 +0x38
github.com/urfave/cli.HandleAction(0x15b1400, 0xc0000c1730, 0xc0000a42c0, 0x0, 0xc00020c000)
	/Users/rrk/go/src/github.com/urfave/cli/app.go:502 +0xbe
github.com/urfave/cli.Command.Run(0x167fa59, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x169914c, 0x3b, 0x0, ...)
	/Users/rrk/go/src/github.com/urfave/cli/command.go:165 +0x487
github.com/urfave/cli.(*App).Run(0xc0001fe000, 0xc0000be000, 0x2, 0x2, 0x0, 0x0)
	/Users/rrk/go/src/github.com/urfave/cli/app.go:259 +0x6e3
main.main()
	/Users/rrk/go/src/github.com/koblas/s3-cli/main.go:172 +0xf15

**Comment by rrkanna** [comment]
Hi Koblas
it didnt work , it still trying to use defaults.

./s3-cli ls --config ~/.s3cfg
InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

if i dont use --config , it just panics
./s3-cli ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x14f9415

**Comment by rrkanna** [comment]
Also is it possible to enable --debug ? Thank you

**Comment by rrkanna** [comment]
Hi Koblas

I was able get around with endpoint using Endpoint s3Config. Please revert your changes since it is panics for default without --config

Thanks you

**Comment by koblas** [comment]
Sorry about that.

Figured out a reasonable way to test it and found the underlying error.  Turns out that s3cmd doesn't use python format ini files -- which are defined to do key lookups on "%(xxxx)s" sections of the valuee.  The golang version if it can't find the value ends up dereferencing a nil pointer an crashes.

Figured out an ugly little fix to resolve the issue and have made the update
